from typing import Literal

TRANSACTION_TYPE = Literal["EXCHANGE", "STAKE", "TRANSFER", "REWARD"]
MESSAGE_TYPE = Literal[
    "DISCOVERY", "TRANSACTION", "BLOCK", "BLOCKCHAINREQUEST", "BLOCKCHAIN", "ROLLBACK"
]
